# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OffboardingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("developer_email", models.CharField(db_index=True, max_length=256)),
                ("project", models.CharField(max_length=256)),
                ("offboard_date", models.DateField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("handover_complete", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-offboard_date"],
            },
        ),
    ]
