# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransitionSheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransitionRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("developer_email", models.CharField(db_index=True, max_length=256)),
                ("previous_project", models.CharField(blank=True, max_length=256, null=True)),
                ("new_project", models.CharField(max_length=256)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("receiving_manager", models.CharField(blank=True, max_length=256, null=True)),
                ("reference", models.CharField(blank=True, max_length=256, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="transitions.transitionsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["developer_email"],
            },
        ),
    ]
