# Generated by ChatGPT
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=512)),
                ("method", models.CharField(max_length=8)),
                ("remote_addr", models.CharField(blank=True, max_length=64, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("app", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=128)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Activity Log Entry",
                "verbose_name_plural": "Activity Log Entries",
            },
        ),
    ]
